import { expect, test } from '@playwright/test';
import path from 'node:path';

test('register, import, identify, replay and explore an unchanged mainline', async ({ page }, info) => {
  const failures: string[] = [];
  let analysisEvents = 0;
  let positionEvents = 0;
  page.on('websocket', socket => socket.on('framereceived', frame => {
    if (typeof frame.payload === 'string' && frame.payload.includes('jobProgress') && frame.payload.includes('analysis')) analysisEvents++;
    if (typeof frame.payload === 'string' && frame.payload.includes('jobProgress') && frame.payload.includes('"kind":"position"')) positionEvents++;
  }));
  page.on('pageerror', e => failures.push(e.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'New here? Create an account' }).click();
  await page.getByLabel('Email', { exact: true }).fill(`e2e-${info.project.name}-${Date.now()}@test.example`);
  await page.getByLabel('Password', { exact: true }).fill('ChessLens.E2e2026!');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A little reflection. A better next game.' })).toBeVisible({ timeout: 15000 });
  await page.getByRole('link', { name: 'Import your first games' }).click();
  await page.locator('input[type=file]').setInputFiles(path.resolve('../samples/first-review.pgn'));
  await page.getByRole('button', { name: 'Import games', exact: true }).click();
  await expect(page.getByText('2 imported · 0 already in library · 0 could not be imported')).toBeVisible({ timeout: 30000 });
  await page.getByRole('link', { name: 'Open library →' }).click();
  await page.locator('.game-row').filter({ hasText: 'Italian Game' }).click();
  await page.getByRole('button', { name: 'I played white · Learner' }).click();
  await expect(page.getByRole('heading', { name: 'Which player were you?' })).toHaveCount(0);
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('starting position');
  await page.getByRole('button', { name: 'Next move', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('After e4');
  await page.getByRole('button', { name: 'Last position' }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('After d6');
  await page.getByRole('button', { name: 'First position' }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('starting position');
  await page.getByLabel('Coordinate move').fill('d2d4');
  await page.getByRole('button', { name: 'Play move', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('Exploring an alternative line');
  await page.getByRole('button', { name: 'Return to mainline' }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('starting position');
  await page.getByRole('button', { name: 'Flip board' }).click();
  await page.getByRole('button', { name: 'Move 7: O-O', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('After O-O');
  await expect(page.getByRole('button', { name: 'Move 7: O-O', exact: true })).toHaveAttribute('aria-current', 'step');
  await page.getByRole('button', { name: 'Analyse game', exact: true }).click();
  await expect(page.getByText('completed · quick review · 10/10 half-moves')).toBeVisible({ timeout: 150000 });
  expect(analysisEvents).toBeGreaterThan(0);
  await expect(page.getByRole('region', { name: 'Game evaluation' })).toBeVisible();
  await page.getByRole('button', { name: /Evaluation at half-move 3:/ }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('After Nf3');
  await expect(page.getByRole('button', { name: 'Move 3: Nf3', exact: true })).toHaveAttribute('aria-current', 'step');
  await page.getByRole('button', { name: 'Analyse this position', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Position analysis status' })).toContainText('Position reviewed', { timeout: 150000 });
  await expect(page.getByLabel('Candidate continuations')).toContainText('Candidate 1');
  expect(positionEvents).toBeGreaterThan(0);
  await page.getByRole('button', { name: 'Move 1: e4', exact: true }).click();
  await page.getByRole('button', { name: 'Move 4: Nc6', exact: true }).click();
  await expect(page.getByRole('status', { name: 'Position status' })).toContainText('After Nc6');
  await expect(page.getByRole('status', { name: 'Position analysis status' })).toContainText('Position reviewed', { timeout: 30000 });
  await expect(page.getByLabel('Candidate continuations')).toContainText('for White');
  const activeBounds = await page.evaluate(() => ({ content: document.documentElement.scrollWidth, viewport: document.documentElement.clientWidth }));
  expect(activeBounds.content).toBeLessThanOrEqual(activeBounds.viewport + 1);
  await page.screenshot({ path: `test-results/candidates-${info.project.name}.png`, fullPage: true });
  await page.getByRole('button', { name: 'Stop position analysis', exact: true }).click();
  await expect(page.getByLabel('Candidate continuations')).toHaveCount(0);
  await page.screenshot({ path: `test-results/review-${info.project.name}.png`, fullPage: true });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1);
  expect(overflow).toBe(false);
  expect(failures).toEqual([]);
});
