import { expect, test } from '@playwright/test';

test('a real missed mate becomes a persisted puzzle with hints, playback and an exact source link', async ({ page }, info) => {
  test.setTimeout(300000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  let puzzleProgress = false;
  page.on('websocket', socket => socket.on('framereceived', frame => { if (frame.payload.toString().includes('"kind":"puzzle"')) puzzleProgress = true; }));
  await page.goto('/'); await page.getByRole('button', { name: 'New here? Create an account' }).click();
  await page.getByLabel('Email', { exact: true }).fill(`puzzle-e2e-${info.project.name}-${Date.now()}@test.example`);
  await page.getByLabel('Password', { exact: true }).fill('ChessLens.E2e2026!'); await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A little reflection. A better next game.' })).toBeVisible({ timeout: 15000 });
  const headers = { 'X-CSRF-TOKEN': (await (await page.request.get('/api/account/csrf')).json()).token };
  // Original labelled fixture: Black misses mate once, then mates after a3.
  const pgn = '[Event "Original missed-mate training fixture"]\n[White "Fixture opponent"]\n[Black "Learner"]\n[Result "0-1"]\n\n1. f3 e5 2. g4 Nc6 3. a3 Qh4# 0-1';
  const imported = await page.request.post('/api/imports/pgn', { headers, data: { pgn, playerName: 'Learner', maxGames: 1 } });
  expect(imported.status()).toBe(202); const importId = (await imported.json()).id;
  await expect.poll(async () => (await (await page.request.get(`/api/jobs/${importId}`)).json()).state, { timeout: 30000 }).toBe('completed');
  const game = (await (await page.request.get('/api/games')).json()).items[0];
  const queued = await page.request.post(`/api/games/${game.id}/analysis`, { headers, data: { profile: 'deep' } }); expect(queued.status()).toBe(202);
  const runId = (await queued.json()).id;
  await expect.poll(async () => (await (await page.request.get(`/api/analysis/${runId}`)).json()).state, { timeout: 120000, intervals: [1000, 2000] }).toBe('completed');
  await page.goto(`/#/games/${game.id}?ply=4&run=${runId}`);
  await expect(page.getByRole('button', { name: 'Turn this decision into a puzzle' })).toBeVisible({ timeout: 15000 });
  await page.getByRole('button', { name: 'Turn this decision into a puzzle' }).click();
  const validation = page.getByRole('status', { name: 'Puzzle validation status' });
  await expect(validation).toHaveText(/Validated and ready to solve\.|Puzzle validation: (rejected|failed|cancelled)\./, { timeout: 180000 });
  await expect(validation).toHaveText('Validated and ready to solve.');
  expect(puzzleProgress).toBe(true);
  await page.getByRole('button', { name: 'Start or resume puzzle' }).click();
  await expect(page.getByRole('heading', { name: 'Find your continuation' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Review the original mistake' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Replay solution' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Get a hint' }).click();
  await expect(page.getByText('Look for forcing checks and the king\'s escape squares.')).toBeVisible();
  const attemptUrl = page.url(); await page.reload();
  await expect(page.getByText('1 hints used. Help changes your review interval.')).toBeVisible();
  await page.screenshot({ path: `test-results/puzzle-solving-${info.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true);
  await page.getByLabel('Coordinate move', { exact: true }).fill('d8h4'); await page.getByRole('button', { name: 'Play move', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Objective resolved' })).toBeVisible();
  await expect(page.getByRole('status', { name: 'Puzzle attempt status' })).toContainText('Attempt solved with assistance.');
  await page.getByRole('button', { name: 'Replay solution' }).click(); await page.getByRole('button', { name: 'Next solution move' }).click();
  await expect(page.getByLabel('Solution notation')).toHaveText('Qh4#');
  await page.screenshot({ path: `test-results/puzzle-solved-${info.project.name}.png`, fullPage: true });
  const source = page.getByRole('link', { name: 'Review the original mistake' });
  await expect(source).toHaveAttribute('href', `#/games/${game.id}?ply=4&run=${runId}`);
  await source.click(); await expect(page.locator('[aria-label="Move 4: Nc6"]')).toHaveAttribute('aria-current', 'step');
  await page.goto(attemptUrl); await expect(page.getByRole('heading', { name: 'Objective resolved' })).toBeVisible();
  await page.getByRole('button', { name: 'Try again', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Find your continuation' })).toBeVisible();
  await expect(page.getByText('0 hints used. Help changes your review interval.')).toBeVisible();
  expect(errors).toEqual([]);
});
